INSERT INTO categories (category_name) VALUES 
('keycaps'), 
('deskmats'), 
('desk'), 
('standing desk'), 
('gaming desk'), 
('console'),
('console accessory'), 
('switch game'), 
('paid dlc'), 
('pokemon'), 
('mario'), 
('animal crossing'),
('stream decks'), 
('capture cards'), 
('web cams'),
('mics'), 
('laptops'), 
('desktops'), 
('tablet'), 
('watches'), 
('monitors'), 
('keyboard'), 
('split'), 
('ortholinear'),
('low profile'), 
('switches'),
('sanriio'), 
('sailor moon'),
('monitors'),
('clicky'),
('linear'),
('tactile'),
('card cover'),
('on sale'),
('out of stock');